### ISSUE TITLE
Crash on settings save

### ISSUE THREAD

**Issue by jimt** [n7tae/DigitalVoice#1]
After building and installing e63a694 and then filling in the settings dialog, the first time I clicked **OK** resulted in a crash.  It does appear to have stored my settings correctly, and after restarting the application I can open settings and click **OK** without issue.

```(qdv:15159): glibmm-ERROR **: 18:57:48.800: 
unhandled exception (type std::exception) in signal handler:
what: basic_string::at: __n (which is 18446744073709551615) >= this->size() (which is 8)

[1]    15159 trace trap (core dumped)  bin/qdv
```

**Comment by n7tae** [comment]
fixed.
